# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Restart RSD-as-a-service"
  community.docker.docker_compose:
    project_name: "{{ rsd_compose_project_name }}"
    project_src: "{{ rsd_working_directory }}"
    state: "present"
    recreate: "always"
    pull: "{{ pull_images }}"
  when: "working_directory.stat.exists"

- name: "Restart nginx"
  community.docker.docker_compose:
    project_name: "{{ rsd_compose_project_name }}"
    project_src: "{{ rsd_working_directory }}"
    services: "nginx"
    state: "present"
    recreate: "always"
    pull: "{{ pull_images }}"
  when: "working_directory.stat.exists"
